#!/usr/bin/env bash
echo "${*:2}"
host=${2:-example.com}
lowest=10000

while read DNS;do
  if [ -n "$DNS" ]; then
    server=$(echo "$DNS" | cut -d$'\t' -f1)
    server_name=$(echo "$DNS" | cut -d$'\t' -f2)
    d=$(dig @"$server" $host | grep "Query time")
    time=${d##;; Query time:}
    time=${time/%msec/}
    printf "%20s%12s%10sms\n" "$server" "$server_name" "$time"
    if [ "$time" -lt $lowest ]; then
    	lowest=$time
    	lowest_server=$server
    	lowest_server_name=$server_name
		fi
  fi
done < ./ipv4.csv

printf "\nLowest is %s %s %sms\n" "$lowest_server" "$lowest_server_name" "$lowest"
